/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedBuddyRouteImport } from './routes/_authenticated/buddy'
import { Route as AuthenticatedCareRouteImport } from './routes/_authenticated/care'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTherapistDeskRouteImport } from './routes/_authenticated/therapist-desk'
import { Route as AuthenticatedTherapistsRouteImport } from './routes/_authenticated/therapists'
import { Route as ApiPublicCronJournalRemindersRouteImport } from './routes/api/public/cron/journal-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuddyRoute = AuthenticatedBuddyRouteImport.update({
  id: '/buddy',
  path: '/buddy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareRoute = AuthenticatedCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTherapistDeskRoute =
  AuthenticatedTherapistDeskRouteImport.update({
    id: '/therapist-desk',
    path: '/therapist-desk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTherapistsRoute = AuthenticatedTherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCronJournalRemindersRoute =
  ApiPublicCronJournalRemindersRouteImport.update({
    id: '/api/public/cron/journal-reminders',
    path: '/api/public/cron/journal-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/buddy': typeof AuthenticatedBuddyRoute
  '/care': typeof AuthenticatedCareRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/therapist-desk': typeof AuthenticatedTherapistDeskRoute
  '/therapists': typeof AuthenticatedTherapistsRoute
  '/api/public/cron/journal-reminders': typeof ApiPublicCronJournalRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/buddy': typeof AuthenticatedBuddyRoute
  '/care': typeof AuthenticatedCareRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/therapist-desk': typeof AuthenticatedTherapistDeskRoute
  '/therapists': typeof AuthenticatedTherapistsRoute
  '/api/public/cron/journal-reminders': typeof ApiPublicCronJournalRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/buddy': typeof AuthenticatedBuddyRoute
  '/_authenticated/care': typeof AuthenticatedCareRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/therapist-desk': typeof AuthenticatedTherapistDeskRoute
  '/_authenticated/therapists': typeof AuthenticatedTherapistsRoute
  '/api/public/cron/journal-reminders': typeof ApiPublicCronJournalRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/archive'
    | '/buddy'
    | '/care'
    | '/journal'
    | '/moderation'
    | '/rewards'
    | '/settings'
    | '/therapist-desk'
    | '/therapists'
    | '/api/public/cron/journal-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/archive'
    | '/buddy'
    | '/care'
    | '/journal'
    | '/moderation'
    | '/rewards'
    | '/settings'
    | '/therapist-desk'
    | '/therapists'
    | '/api/public/cron/journal-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/archive'
    | '/_authenticated/buddy'
    | '/_authenticated/care'
    | '/_authenticated/journal'
    | '/_authenticated/moderation'
    | '/_authenticated/rewards'
    | '/_authenticated/settings'
    | '/_authenticated/therapist-desk'
    | '/_authenticated/therapists'
    | '/api/public/cron/journal-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronJournalRemindersRoute: typeof ApiPublicCronJournalRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buddy': {
      id: '/_authenticated/buddy'
      path: '/buddy'
      fullPath: '/buddy'
      preLoaderRoute: typeof AuthenticatedBuddyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/care': {
      id: '/_authenticated/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof AuthenticatedCareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/therapist-desk': {
      id: '/_authenticated/therapist-desk'
      path: '/therapist-desk'
      fullPath: '/therapist-desk'
      preLoaderRoute: typeof AuthenticatedTherapistDeskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/therapists': {
      id: '/_authenticated/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof AuthenticatedTherapistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/journal-reminders': {
      id: '/api/public/cron/journal-reminders'
      path: '/api/public/cron/journal-reminders'
      fullPath: '/api/public/cron/journal-reminders'
      preLoaderRoute: typeof ApiPublicCronJournalRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedBuddyRoute: typeof AuthenticatedBuddyRoute
  AuthenticatedCareRoute: typeof AuthenticatedCareRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTherapistDeskRoute: typeof AuthenticatedTherapistDeskRoute
  AuthenticatedTherapistsRoute: typeof AuthenticatedTherapistsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedBuddyRoute: AuthenticatedBuddyRoute,
  AuthenticatedCareRoute: AuthenticatedCareRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTherapistDeskRoute: AuthenticatedTherapistDeskRoute,
  AuthenticatedTherapistsRoute: AuthenticatedTherapistsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronJournalRemindersRoute: ApiPublicCronJournalRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
